[DRAT] Fix/issue 97 fix future date test from articles post file
kat-kan/kawqa-gad-playwright pull request #102
Opened 2024-06-01 20:29 UTC by kat-kan

## Resolves #97 

### Scope of changes:

Started as fix, evolved into testing more date formats.
This is a draft as I want Your opinion if You like this idea.

### How to use it:

N/A

## Any other comments?

...

Before submitting Pull Request, I've ensured that:

- [ ] The PR is associated with the relevant Issue before its creation.
- [ ] All new and existing tests passed
- [ ] My commit messages follow the `kawqa-gad-playwright` project's [git commit message format](https://github.com/kat-kan/kawqa-gad-playwright/blob/main/CONTRIBUTING.md).

2024-06-24 13:13 UTC, Justyna-KO commented
@kat-kan 
I think it's a good idea to perform our tets for different dates. 
I like that we don't duplicate the code for these tests thanks to the loop. 
One test fails with me: 
Returns 201 Created after creating article with date 2023-06-24T13:05:45.155Z
Expected: 201
Received: 422
There is a problem with the appropriate assertions for different dates.

2024-06-24 14:09 UTC, Slawomir-DKl requested changes
@kat-kan Great changes! BTW, acc. to https://github.com/jaktestowac/gad-gui-api-demo/releases/tag/v2.6.6, the new version brings fixes in validation of article creation date. The fixes cause both tests "Returns 201 Created after creating article with date" to fail (the tests pass in 2.6.5). I'll try to investigate this today evening and maybe ask Krzysztof about this.

2024-06-30 09:30 UTC, Slawomir-DKl submitted a review, later dismissed

2024-06-30 09:30 UTC, Slawomir-DKl commented on tests/api/articles/articles-post.spec.ts
>    const articleTitle: string =
I've found the reason for the bad result of the "Returns 201 Created..." test. GAD 2.6.6 brings the validation of article title uniqueness - see https://github.com/jaktestowac/gad-gui-api-demo/releases/tag/v2.6.6. Therefore the first run gives one failed test (first POST is OK, 2nd post gives the response
`info: { error: { message: 'Field "title" is not unique!' } }`
I see two solutions:
- restoring DB after each test (which can be troublesome and, in my opinion, is not optimal)
- adding sth like `randomNumber: string = Math.random().toString()` to `articleTitle` variable (note: it must be added also inside the test - due to the loop it is not enough to add the randomization to `test.describe`)

What do you think?

2024-06-30 09:31 UTC, Slawomir-DKl commented
> @kat-kan I think it's a good idea to perform our tets for different dates. I like that we don't duplicate the code for these tests thanks to the loop. One test fails with me: Returns 201 Created after creating article with date 2023-06-24T13:05:45.155Z Expected: 201 Received: 422 There is a problem with the appropriate assertions for different dates.

@Justyna-KO @kat-kan I've found the reason. Please take look at the comment to the line 16

2024-07-05 19:57 UTC, kat-kan commented on tests/api/articles/articles-post.spec.ts
>    const articleTitle: string =
As discussed in the last meeting, both ways are fine and another one is using Faker. No matter which one - I'd prefer to address it in another PR (makes repository history cleaner and more readable later)

2024-07-05 20:00 UTC, kat-kan commented on tests/api/articles/articles-post.spec.ts
> +      const futureDateFormatted: string = invalidDate;
You are right, I removed it

2024-07-07 15:02 UTC, Justyna-KO approved these changes

2024-07-07 17:27 UTC, kat-kan commented
@Justyna-KO @Slawomir-DKl and any others who'd like to contribute in code review:
as the idea to run tests against different data formats is approved, I removed draft type from PR. I believe it is ready to merge. I added Your suggestions. 
The tests parameterization is yet to be introduced in comments tests - I will create another issue for this task.
I will also create issue for unique article titles (new validation in GAD that was mentioned by @Slawomir-DKl)

2024-09-09 18:42 UTC, Justyna-KO approved these changes

2024-09-28 07:07 UTC, merged