tests/ISSUE-103_accessibility_tests
kat-kan/kawqa-gad-playwright pull request #104
Opened 2024-06-27 16:30 UTC by Justyna-KO

## Resolves #103 

### Scope of changes:

Accessibility tests for:
-welcome page
-main page
-Let's check button
-Comments button

### How to use it:

  install @axe-core/playwright

## Any other comments?

Before submitting Pull Request, I've ensured that:

- [ ] The PR is associated with the relevant Issue before its creation.
- [ ] All new and existing tests passed
- [ ] My commit messages follow the `kawqa-gad-playwright` project's [git commit message format](https://github.com/kat-kan/kawqa-gad-playwright/blob/main/CONTRIBUTING.md).

2024-09-16 17:46 UTC, kat-kan submitted a review, later dismissed
I believe this is a good start for accessibility tests solution in our project.
IMO the target solution should be directed at using Page Object Pattern and be consistent with (not existing at the moment) UI tests solution.
Another thing that we could consider in the future is finding the alternative for skipping tests that are failing but we still want to keep them, Maybe exclude them by tag?  
But I believe these are not things that we can address right now so approve from my side :)

2024-09-24 20:55 UTC, Slawomir-DKl requested changes
Great experience - sth definitely worth learning. Thank you!

2024-09-24 20:55 UTC, Slawomir-DKl commented on tests/accessibility/welcome-page.spec.ts
> +    .withTags('wcag21a', 'wcag21aa')
According to [AXE-Core Readme](https://github.com/dequelabs/axe-core-npm/blob/develop/packages/playwright/README.md), the option `withTags` requires string or array, ie. here it should be `.withTags(['wcag21a', 'wcag21aa'])` (I use "@axe-core/playwright": "^4.10.0")

2024-09-24 20:55 UTC, Slawomir-DKl commented on tests/accessibility/main-page.spec.ts
> +  await testInfo.attach('accesibility-scan-results', {
A typo - `accesibility` => `accessibility`

2024-09-24 20:55 UTC, Slawomir-DKl commented on package.json
> +    "@axe-core/playwright": "^4.9.1"
The current version is 4.10.0 - maybe it would be good to have a current version as for the merge time

2024-09-28 07:14 UTC, kat-kan commented on package.json
> +    "@axe-core/playwright": "^4.9.1"
We can update, but I'd like to note that it is not a general practice to update to latest version of library before the merge as changes were created and tested for the exact version. Here the scope is small so risk is low, but you can imagine what can be caused by rushing library update for bigger chunk of code :)

2024-09-28 16:08 UTC, Justyna-KO commented on package.json
> +    "@axe-core/playwright": "^4.9.1"
If this is not general practice, I would leave it as is.

2024-09-28 16:12 UTC, Justyna-KO commented on tests/accessibility/main-page.spec.ts
> +  await testInfo.attach('accesibility-scan-results', {
I changed it.

2024-09-28 16:15 UTC, Justyna-KO commented on tests/accessibility/welcome-page.spec.ts
> +    .withTags('wcag21a', 'wcag21aa')
I've corrected it.

2024-09-28 16:16 UTC, Slawomir-DKl commented on package.json
> +    "@axe-core/playwright": "^4.9.1"
I haven't thought about the potential problems. Of course, you're right

2024-09-28 16:30 UTC, Slawomir-DKl submitted a review, later dismissed
Thank you for the changes.

2024-09-28 17:13 UTC, Slawomir-DKl approved these changes

2024-09-28 17:19 UTC, merged