[ISSUE#23]PUT articles/{id}- add tests
kat-kan/kawqa-gad-playwright pull request #111
Opened 2024-07-21 19:48 UTC by Justyna-KO

## Resolves #23

### Scope of changes:
Tests PUT articles/{id} for responses:
- 200: article updated
- 201: article created
- 400: Bad request - malformed JSON
- 404: Unauthorized
- -422: Invalid article supplied

### How to use it:

## Any other comments?
The test for the 404 response is missing, any ideas on how to get 404 in response for this endpoint? 

Before submitting Pull Request, I've ensured that:

- [ ] The PR is associated with the relevant Issue before its creation.
- [ ] All new and existing tests passed
- [ ] My commit messages follow the `kawqa-gad-playwright` project's [git commit message format](https://github.com/kat-kan/kawqa-gad-playwright/blob/main/CONTRIBUTING.md).

2024-07-22 14:33 UTC, kat-kan commented on tests/api/articles/articles-is-put.spec.ts
> +  const articleId: number = Math.floor(Math.random() * (1000 - 100 + 1)) + 100;
Looks like this expression is the very same as in line 10 so it could be saved in the variable. 
Another thing is that according to GAD repo page, validation of unique title is currently (from GAD 2.7.0) triggered with feature flag. So unless feature flag is on, there is no need to generate unique title

2024-07-22 14:36 UTC, kat-kan commented on tests/api/articles/articles-is-put.spec.ts
> +  test('Returns 201 OK status code when updating article', async ({
This is a specific situation when PUT is used to create new article, I think better description is "...when creating article" or "...when creating article using PUT"

2024-07-22 14:37 UTC, kat-kan commented on tests/api/articles/articles-is-put.spec.ts
> +  test('Returns 422 Unprocessable content after updating  article with wrong date format', async ({
looks like there is an additional space between updating and article

2024-07-22 14:38 UTC, kat-kan reviewed
This is my initial review - I do not have access to coding env this week so I'll get back to this PR

2024-08-05 19:20 UTC, Slawomir-DKl commented
@Justyna-KO The latest GAD version (2.7.2) brings another logic which is not yet tested:

_using PUT with empty body will return error 422 (comments, users, articles)_ 

If you think about developing the tests further, it would be quite nice extension

2024-09-18 20:52 UTC, kat-kan commented on tests/api/articles/article-id-put.spec.ts
> +  test.describe('PUT articles/{id} endpoint tests with enabled feature', async () => {
I like the additional tests, good job 👍🏼 
I do have small concern about naming - imagine that you do not have access to test code and need to understand test results based on test report only. So based on the test description we know that some feature was enabled (or that validation on title was enabled) but it's still not clear.
Also - if we add test.describe() for group of tests, report will show this + value from each test. Which means that we can write about this enabled validation only on test group level, it will be enough.
To sum up, I'd recommend to try adding more specific info about enabled validation of unique title, removing it from test() level. Lemme know what You think and if such report would be more readable :)

2024-09-18 20:53 UTC, kat-kan commented on tests/api/articles/article-id-put.spec.ts
> +    test('Returns 201 Created status code when updating article - enabled validation on the title', async ({
Aren't these 2 descriptions (this one and the one above) mixed? 201 Created should be returned when sth is..created?

2024-09-23 21:20 UTC, Justyna-KO commented on tests/api/articles/article-id-put.spec.ts
> +    test('Returns 201 Created status code when updating article - enabled validation on the title', async ({
Yes, you're right.

2024-09-23 21:20 UTC, Justyna-KO commented on tests/api/articles/article-id-put.spec.ts
> +  test.describe('PUT articles/{id} endpoint tests with enabled feature', async () => {
good point, I changed it

2024-09-25 22:51 UTC, Slawomir-DKl reviewed
Please take a look at my comments. I'm not sure if they require changes - I leave it to you.

2024-09-25 22:51 UTC, Slawomir-DKl commented on tests/api/articles/article-id-put.spec.ts
> +      "title: ${newTitle},  // error: missing closing quotation mark
The problem is not only in the closing quotation mark - the whole string is formatted incorrectly.

I tried to construct proper JSON (nice exercise, by the way).
If I properly understand the [Playwright documentation](https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-put), `data` option serializes its parameter to JSON, therefore I used JSON.parse method to debug - I added two lines for debugging purposes only: 
```
const malJson = JSON.parse(malformedJson);
console.log(malJson);
```
This way I stated that here the problems are:
- newline characters (parser doesn't recognize properties, as they are after newlines)
- lacking closing quotation mark, as you stated
- the string in the image should have groups of four slashes instead of two slashes (as it is converted twice)

So, to get a different response status (which was my goal as I checked the test negatively), I had to use the one-line const:
```const malformedJson: string = `{"user_id": "${testUsers.regularUser.id}", "title": "${newTitle}", "body": "${newContent}", "date": "${articleDate}", "image": "src\\\\test-data\\\\images\\\\Roasted_coffee_beans.jpg"}`;```
Such string gives proper status 422 (as the title is not unique)

By the way, I have to check other malformed JSONs in our project - they are constructed similarly.

Of course, the goal is achieved - your string is finally not a proper JSON and the response is 400, but I think we should check each test negatively, too, to understand how it works

If you want to use my one-liner, it should be enough to remove one quotation mark from the string to get the 400 status

2024-09-25 22:51 UTC, Slawomir-DKl commented on tests/api/articles/article-id-put.spec.ts
> +  test.describe('PUT articles/{id} endpoint tests with enabled feature_validate_article_title', async () => {
Great work with the tests with the enabled feature. I learnt a lot from your code. Nevertheless, I failed in attempts to switch the validation on for the first test and switch it off for the second test, so maybe the flag doesn't impact PUT requests. It would be great to create a negative test to show that the flag works and the title is not validated when the flag is set to false. 
Now when I changed the title to "a" in the second test, I got 422 each time (with response body `{ error: { message: 'Field "title" is not unique!' } }`), regardless of setting the flag `true` or `false`.

2024-09-28 07:17 UTC, kat-kan commented on tests/api/articles/article-id-put.spec.ts
> +      "title: ${newTitle},  // error: missing closing quotation mark
I need to admit that I do not quite get it without playing around with all these examples and yes, this malformed json is used in all tests. Can you please talk about it during Monday meeting?

2024-09-28 17:38 UTC, Justyna-KO commented on tests/api/articles/article-id-put.spec.ts
> +  const articleDate: string = '2024-07-14T15:44:31Z';
good point, I've changed it.

2024-09-28 21:44 UTC, Justyna-KO commented on tests/api/articles/article-id-put.spec.ts
> +      "title: ${newTitle},  // error: missing closing quotation mark
we will discuss it at the meeting

2024-09-28 21:45 UTC, Justyna-KO commented on tests/api/articles/article-id-put.spec.ts
> +  test.describe('PUT articles/{id} endpoint tests with enabled feature_validate_article_title', async () => {
I have added corrections, please review.
I've  also added a negative test.

2024-09-29 14:45 UTC, Slawomir-DKl requested changes
Thank you for the changes. I propose two small changes.

2024-09-29 14:45 UTC, Slawomir-DKl commented on tests/api/articles/article-id-put.spec.ts
> +  const oldTilte = 'The difference between Scrum and Kanban';
I've just found that this is a typo. Now: `oldTilte` but it should be: `oldTitle` (replace in the whole file)

2024-09-29 14:45 UTC, Slawomir-DKl commented on tests/api/articles/article-id-put.spec.ts
> +  test.describe('PUT articles/{id} endpoint tests with enabled feature_validate_article_title', async () => {
@Justyna-KO Your new tests allowed me to understand that this feature flag works in PUT requests :-).

What do you think about renaming the new tests (both 200 and 422)? Now the name states `when updating article with the same title`. This can be misleading - firstly, I understood that the title has to be the same as the previous title of the same article, while the title has to be the same as any title in the DB (i.e. it has to be non-unique). What about `when updating the article with the title equal to another article title`?

2024-10-07 21:36 UTC, Justyna-KO commented on tests/api/articles/article-id-put.spec.ts
> +  test.describe('PUT articles/{id} endpoint tests with enabled feature_validate_article_title', async () => {
ok, this will be clearer

2024-10-07 21:37 UTC, Justyna-KO commented on tests/api/articles/article-id-put.spec.ts
> +  const oldTilte = 'The difference between Scrum and Kanban';
I've corrected it.

2024-10-11 21:48 UTC, Slawomir-DKl submitted a review, later dismissed
Thank you for the changes. I think the tests are ready to merge

2024-10-12 06:00 UTC, Slawomir-DKl approved these changes

2024-10-12 08:10 UTC, merged