Issue 108 add testing unique article name
kat-kan/kawqa-gad-playwright pull request #124
Opened 2024-11-02 19:11 UTC by Slawomir-DKl

## Resolves #108 

### Scope of changes:

- I added two tests for creating new articles (POST method) with enabled validation of title uniqueness
- I created a new helper file for enabling/disabling feature flags (`feature-file.helper.ts`)
- I changed the instances of enabling/disabling feature flags in older tests to the new helper
- I added a new article title generator in the test-data folder
- I introduced faker in the project and used it in the unique article generator function
- In the new tests, I proposed a new way of building JSON for the `data` key in the request function

### How to use it:

#### New helper `feature-file.helper.ts`
I propose using the new helper function in hook beforeAll and disabling it in hook afterAll. To use the function, pass the `request` parameter as the context, the name of the flag (to be checked in GAD documentation) and boolean `isEnabled` (`true` if you want to enable the flag and `false` to disable it), e.g.

```await enableFeatureFlag(request, 'feature_validate_article_title', true);```

#### Article title generator
At the moment you can:
- generate unique article title using the faker book library; the function checks if the generated title is not present in the GAD database
- get the title of the first article in the GAD database
To use the function, you have to pass `request` parameter as the context

## Any other comments?

In the `generateUniqueArticleTitle` function, I used the while loop with if condition. Remarks:

- ESLint detects the IF loops and displays warnings, but I think in this case it is justified to use IF, so I skipped ESLint checks for one line
- There is a minimal probability that the faker will generate titles already present in the GAD database. To avoid this, I use the `while` loop, but I didn't enter any measures to stop the loop e.g. after 50 unsuccessful iterations (I think the chances are to small to make such fuses)
- Occasionally some tests are flaky (e.g. `Returns 422 status code when updating the article with the title equal to another article title` with enabled flag in `article-id-put.spec.ts`) when all the tests are fired at once. At the moment I haven't discovered the problem

Before submitting Pull Request, I've ensured that:

- [x] The PR is associated with the relevant Issue before its creation.
- [x] All new and existing tests passed
- [x] My commit messages follow the `kawqa-gad-playwright` project's [git commit message format](https://github.com/kat-kan/kawqa-gad-playwright/blob/main/CONTRIBUTING.md).

2024-11-11 19:03 UTC, Slawomir-DKl commented
Additionally, I've set the article-labels tests to serial mode to avoid flaky tests - in parallel mode, the "200" test sometimes fails with "404" code, probably due to other tests working concomitantly on the same articles or other resources

2024-12-22 15:49 UTC, Slawomir-DKl commented
I changed some soft assertions to hard ones - there is no need to test response body if response.status fails

2024-12-30 13:23 UTC, Justyna-KO submitted a review, later dismissed

2025-01-15 21:15 UTC, Slawomir-DKl commented
@Justyna-KO Nothing has changed since your last review - I've just merged main into this branch (twice)

2025-01-20 22:20 UTC, kat-kan requested changes
Marking as request changes; not because I do actually request all changes, but I'd like to discuss ;) 
These are very nice helpers, shame on me it took so long to review. Can't wait to start using them in the project.

2025-01-20 22:20 UTC, kat-kan commented on test-data/shared/article.generator.ts
> +  const articleTitleList: string[] = articlesJSON.map(
I suggest trying Set instead of array
```
  const titles = new Set(
    articlesJSON.map((article: { title: string }) => article.title)
  );
```
and while checking the existence of title in the list, set's has() method instead of includes()

Benefits:
works more efficient due to construction of Set (using hash table, has() will be very fast regardless of set's size while for array, each item needs to be verified to return result of includes() method)

2025-01-20 22:20 UTC, kat-kan commented on test-data/shared/article.generator.ts
> +  while (!isUnique) {
I think that do...while loop would match better this case and make cleaner code. What do You think?

2025-01-20 22:20 UTC, kat-kan commented on tests/api/article-labels/article-labels.article.id.get.spec.ts
> +test.describe.configure({ mode: 'serial' });
Cool that You've thought of that!

2025-02-01 19:13 UTC, Slawomir-DKl commented on src/helpers/api/feature-flags.helper.ts
> +  flagName: string,
@kat-kan Great idea. I've added issue #164 as I don't want to extend the scope of this task

2025-02-01 19:20 UTC, Slawomir-DKl commented on test-data/shared/article.generator.ts
> +    // eslint-disable-next-line playwright/no-conditional-in-test
At the moment of writing the test, ESLint detected IF conditionals as sth not compliant with the rules, so I've put the comment to allow IF within the test.
Now, as I see, the rule is off (https://getresponse.github.io/eslint-config-getresponse/), so I will remove the comment - it is no longer needed

2025-02-01 19:40 UTC, Slawomir-DKl commented on test-data/shared/article.generator.ts
> +  while (!isUnique) {
I'll change it. Could you check if it is OK?

2025-02-01 19:51 UTC, Slawomir-DKl commented on test-data/shared/article.generator.ts
> +  const articleTitleList: string[] = articlesJSON.map(
@kat-kan Seems like a great idea. Additionally, the set is smaller as it doesn't store duplicates - a few articles could have the same title, and a list stores all of them, while the set stores only the unique ones.

Thank you for the fragment of code, too. I haven't used sets before.

2025-02-01 19:57 UTC, Slawomir-DKl commented
> Marking as request changes; not because I do actually request all changes, but I'd like to discuss ;) These are very nice helpers, shame on me it took so long to review. Can't wait to start using them in the project.

@kat-kan Thank you for the interesting remarks. Again, I've learned new things thanks to your input. Could you please check my changes?

2025-03-03 17:25 UTC, kat-kan approved these changes

2025-03-03 18:13 UTC, merged