[ISSUE #125]Correct flaky tests for PUT articles endpoint
kat-kan/kawqa-gad-playwright pull request #126
Opened 2024-11-02 21:23 UTC by Justyna-KO

## Resolves #123

### Scope of changes:

I changed the range of randomNumber used as the id of the articles.

### How to use it:

..
## Any other comments?

...

Before submitting Pull Request, I've ensured that:

- [ ] The PR is associated with the relevant Issue before its creation.
- [ ] All new and existing tests passed
- [ ] My commit messages follow the `kawqa-gad-playwright` project's [git commit message format](https://github.com/kat-kan/kawqa-gad-playwright/blob/main/CONTRIBUTING.md).

2024-11-11 10:14 UTC, Slawomir-DKl requested changes

2024-11-12 21:15 UTC, Justyna-KO commented on tests/api/articles/article-id-put.spec.ts
> +  const randomNumber = Math.floor(Math.random() * (2000 - 1001 + 1)) + 1001;
I added articleID.generator.ts.

2024-11-12 23:01 UTC, Slawomir-DKl reviewed
Great changes. I've learned a lot from your solutions and now I'll introduce some changes to my PR to be consistent with your ideas such as map() instead of for loop (which I find much better)

I have only two little remarks - for your consideration

2024-11-13 19:38 UTC, Justyna-KO commented on test-data/shared/articleID.generator.ts
> + // get list of all article IDs
ok

2024-11-13 19:44 UTC, Justyna-KO commented on test-data/shared/articleID.generator.ts
I agree.

2024-11-13 19:50 UTC, Slawomir-DKl requested changes

2024-11-13 19:50 UTC, Slawomir-DKl commented on tests/api/articles/article-id-put.spec.ts
> +import { generateUniqueArticleId } from 'test-data/shared/articleID.generator';
Thank you for the changes. After changing the generator file name, you have to change the module to article.generator as well

2024-11-13 19:56 UTC, Slawomir-DKl approved these changes
Thank you again :)

2024-11-13 19:57 UTC, merged