test(simple-elements): add tests, page, and helper for GUI practise page
kat-kan/kawqa-gad-playwright pull request #129
Opened 2024-11-17 14:10 UTC by parira2306

## Resolves #123

### Scope of changes:

- Added a new _SimpleElementsWithIdsPage_ class for managing locators and actions related to the "Simple Elements with IDs" subpage.

- Implemented a helper function _hexToRgb_ for converting HEX colors to RGB, located in the helpers directory.

- Added Playwright tests for the "Simple Elements with IDs" subpage, covering:

Filling input fields (text, date, color).
Clicking buttons and selecting radio buttons.
Testing tooltip visibility.
Testing the range bar behavior and textarea resizing.

     

### How to use it:
Run Playwright tests as usual.

## Any other comments?
--

Before submitting Pull Request, I've ensured that:

- [x] The PR is associated with the relevant Issue before its creation.
- [x] All new and existing tests passed
- [x] My commit messages follow the `kawqa-gad-playwright` project's [git commit message format](https://github.com/kat-kan/kawqa-gad-playwright/blob/main/CONTRIBUTING.md).

2024-11-30 19:53 UTC, Slawomir-DKl commented
I suggest some discussion during the next KawQA meeting:

- The name of the folder (now `gui` which seems to be OK)
- If it is necessary to create the structure e.g.: superclass `PracticePage` and class `SimpleElements` extending the `PracticePage` and class `SimpleElementsWithIdsPage` extending `PracticePage`? For example, the `textAreaStretching` method will also be needed on the other practice pages. Of course, the person who will prepare the tests for the next practice page can then create the structure and move the common elements to the superclass.

2024-11-30 21:13 UTC, Slawomir-DKl requested changes
Thank you for your tests. These are the first GUI tests in our project, so it was really fruitful experience for me. I proposed a few changes. Please consider them.

2024-12-10 20:52 UTC, Slawomir-DKl reviewed
Thank you for your changes. Some methods in your code are completely new to me, therefore I added one comment about bitwise operations. BTW, thanks to you, I've just learned the `parseInt` function.

2024-12-10 20:52 UTC, Slawomir-DKl commented on src/helpers/gui/color-utils.helper.ts
I'm just curious: why do you use BIT operations here? It isn't easy to comprehend at least for beginners and can be replaced e.g. by simpler

```typescript
export function hexToRgb(hex: string): string {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return `${r}, ${g}, ${b}`;
}
```

2024-12-10 20:52 UTC, Slawomir-DKl commented on src/gui/pages/simple-elements-with-ids.page.ts
> +import { Locator } from '@playwright/test';
Maybe it would be better to return to `import { Locator, Page } from '@playwright/test';` in one line? What do you think? It would be shorter and still comprehensible

2025-01-04 18:44 UTC, Justyna-KO commented
> I suggest some discussion during the next KawQA meeting:
> 
> * The name of the folder (now `gui` which seems to be OK)
> * If it is necessary to create the structure e.g.: superclass `PracticePage` and class `SimpleElements` extending the `PracticePage` and class `SimpleElementsWithIdsPage` extending `PracticePage`? For example, the `textAreaStretching` method will also be needed on the other practice pages. Of course, the person who will prepare the tests for the next practice page can then create the structure and move the common elements to the superclass.

@parira2306 @Slawomir-DKl 
Maybe it would be better to have the main folder named GUI, and under it make subfolders such as simple-elements?

2025-01-04 18:45 UTC, Justyna-KO approved these changes

2025-01-09 18:17 UTC, parira2306 commented on src/gui/pages/simple-elements-with-ids.page.ts
> +import { Locator } from '@playwright/test';
Yes, of course you're right. I corrected it

2025-01-09 18:21 UTC, parira2306 commented on src/helpers/gui/color-utils.helper.ts
I knew what the effect was supposed to be, but I didn't know how to achieve it. This feature is the result of my internet research. Your version also works, and it's much simpler, so I'll use it :)

2025-01-10 23:15 UTC, Justyna-KO approved these changes

2025-01-13 18:58 UTC, kat-kan approved these changes
Thank you for the contribution (and ofc, thanks to @Slawomir-DKl for thoughtful ideas)
This is a very clean and organized code.
I'm really happy we have more type of tests in our repository!

2025-01-13 18:58 UTC, kat-kan commented on src/helpers/gui/color-utils.helper.ts
> +// //Function to convert color from HEX to RGB
I noticed a doubled comment indication - but that's not a blocker for merge, of course ;)

2025-01-13 19:00 UTC, parira2306 commented on src/helpers/gui/color-utils.helper.ts
> +// //Function to convert color from HEX to RGB
Thank you for your kind words and code review :)

2025-01-13 19:28 UTC, Slawomir-DKl approved these changes

2025-01-13 19:28 UTC, merged