[Issue#25] add test API for DELETE by id for article
kat-kan/kawqa-gad-playwright pull request #35
Opened 2023-11-08 10:59 UTC by adamcegielka

This is a draft to verify the API request for POST and DELETE method

2023-11-14 20:54 UTC, kat-kan submitted a review, later dismissed

2024-01-02 22:09 UTC, kat-kan reviewed
General comment:
I think that we agreed to add Given/When/Then in all tests. Especially in this test it would be beneficial - would make more obvious why the article is created at first. I'm not pushing, but you can consider adding GWT comments :)

2024-02-05 18:08 UTC, kat-kan commented on tests/api/articles-id-delete.spec.ts
> +  // Error - Received: 401
Agreed 5.02:
- reason it fails is because regular user can try to delete only his/her article
- would be nice to add 2 different tests, for regular user and admin

2024-02-05 18:13 UTC, bugITwhisperer commented on tests/api/articles-delete-by-id.spec.ts
> +  });
This has been discussed during the meting - the issue can be resovled:)

2024-02-05 18:16 UTC, bugITwhisperer requested changes

2024-02-05 18:16 UTC, bugITwhisperer commented on tests/api/articles-id-delete.spec.ts
> +  const baseURL: string = process.env.BASE_URL;
as discussed this can be deleted

2024-02-05 18:16 UTC, bugITwhisperer commented on tests/api/articles-id-delete.spec.ts
> +  const articles: string = `${baseURL}/api/articles/`;
baseURL part can be deleted

2024-10-13 14:41 UTC, Slawomir-DKl commented on tests/api/articles-id-delete.spec.ts
> +  const baseURL: string = process.env.BASE_URL;
I deleted it

2024-10-13 14:42 UTC, Slawomir-DKl commented on tests/api/articles-id-delete.spec.ts
> +  const articles: string = `${baseURL}/api/articles/`;
I've deleted it

2024-10-13 14:42 UTC, Slawomir-DKl commented on tests/api/articles-id-delete.spec.ts
> +  test("returns 404 status code when delete a non-existent article", async ({ request }) => {
Now it gives 404

2024-10-23 21:00 UTC, Slawomir-DKl commented on tests/api/articles-id-delete.spec.ts
> +  });
Added as new issue #121

2024-10-23 21:03 UTC, Slawomir-DKl commented
I had to add 500 ms delay between creating and deleting the article. Without such delay the tests are flaky - randomly pass or fail (with 404 status). I know that it would be better to avoid such additional waits, but at the moment I didn't find any smarter solution.
If it is acceptable at the moment, I would add new issue for finding better solution.

2024-10-26 11:07 UTC, Slawomir-DKl commented
I've finally found some solution to the flakiness. According to Krzysiek, there is a delay between POST request and the actual creation of the asset. To solve this (and of course to practice new things) I used the polling technique

2024-11-02 20:20 UTC, Justyna-KO commented on tests/api/articles/articles-id-delete.spec.ts
> +  });
I would suggest removing the spaces before the comments, and adding before this test for better readability. 

great work!  especially with the solution for the flaky test

2024-11-02 20:20 UTC, Justyna-KO approved these changes

2024-11-03 09:51 UTC, Justyna-KO commented
> I've finally found some solution to the flakiness. According to Krzysiek, there is a delay between POST request and the actual creation of the asset. To solve this (and of course to practice new things) I used the polling technique

I ran these tests locally several times and they are still flaky.
Maybe the timeout should be longer?

2024-11-07 21:42 UTC, Slawomir-DKl commented
> > I've finally found some solution to the flakiness. According to Krzysiek, there is a delay between POST request and the actual creation of the asset. To solve this (and of course to practice new things) I used the polling technique
> 
> I ran these tests locally several times and they are still flaky. Maybe the timeout should be longer?

I've modified intervals to change the behaviour of the assertion. It seems that it works now.

BTW, I've done some refactoring, moving similar parts to describe part

2024-11-07 21:44 UTC, Slawomir-DKl commented on tests/api/articles/articles-id-delete.spec.ts
> +  });
The empty line before "Then" and "When" allows the test to be visually divided into separate sections.
Of course, I've added the newline between each of the tests.

2024-11-12 22:24 UTC, merged