[ISSUE#20] GET articles/ - add test
kat-kan/kawqa-gad-playwright pull request #57
Opened 2023-11-26 23:03 UTC by KarolinaZakrzewska

## Resolves #20 

### Scope of changes:

- add test: 200 Successful Request  -> When fetching articles is successful.

2023-11-28 08:05 UTC, bugITwhisperer submitted a review, later dismissed

2024-02-03 19:29 UTC, bugITwhisperer requested changes

2024-02-03 19:29 UTC, bugITwhisperer commented on tests/api/articles-endpoint-get.spec.ts
> +    const expectedStatusCode = 200;
This will be no longer required since we have enum with the list of status codes in this change:  https://github.com/kat-kan/kawqa-gad-playwright/pull/50

2024-02-03 19:29 UTC, bugITwhisperer commented on tests/api/articles-endpoint-get.spec.ts
> +test.describe('GET/articles/ Get all articles', async () => {
It's been fixed so I'm resolving issue :)

2024-02-03 19:30 UTC, bugITwhisperer commented on tests/api/articles-endpoint-get.spec.ts
> +    const response: APIResponse = await request.get(`${baseURL}/api/articles/`);
It's been fixed so I'm resolving issue :)

2024-02-05 16:55 UTC, kat-kan commented
As agreed @bugITwhisperer will take over from there

2024-02-18 22:19 UTC, bugITwhisperer approved these changes

2024-02-18 22:20 UTC, merged