[ISSUE#67]POST comments/ - add test
kat-kan/kawqa-gad-playwright pull request #68
Opened 2023-12-28 18:47 UTC by Justyna-KO

## Resolves #67 

Add tests: 201 created, 400 bad request, 422 Invalid comment supplied

2023-12-29 15:33 UTC, kat-kan commented
@Justyna-KO congrats on your first PR 🥳
You will be able to merge after receiving 2 approvals during code review.

PS please make use of our PR/issue templates (the autogenerated description with gaps to be filled visible when you create issue/PR). 
We use it as a standard and to help each other understand the scope of task.

2024-01-20 21:37 UTC, kat-kan approved these changes
Thank you for your patience :)
overall, awesome job! 
My two cents on PR:
1. Please use Prettier and you won't have to worry about formatting problems like redundant empty lines.
2. The branch name does not match the agreed pattern. Didn't you encounter problems while committing? The branch name is validated and the example of valid name is "tests/ISSUE-16_Post_Login_endpoint_tests"

2024-01-20 21:37 UTC, kat-kan commented on tests/api/comments-post.spec.ts
> +    //When user sends POST request to Comments endpoint
I appreciate your adding detailed comments :) however, the standard we agreed on is just Given/When/Then and the necessary comments about some logic that needs additional explanation. It's not a big deal but I'd recommend deleting every comment except these Given/When/Then

2024-01-20 21:37 UTC, kat-kan commented on tests/api/comments-post.spec.ts
> +
redundant empty line

2024-01-20 21:37 UTC, kat-kan commented on tests/api/comments-post.spec.ts
> +
redundant empty line

2024-01-20 21:37 UTC, kat-kan commented on tests/api/comments-post.spec.ts
> +
redundant empty line

2024-01-27 20:59 UTC, Justyna-KO commented
> Thank you for your patience :) overall, awesome job! My two cents on PR:
> 
> 1. Please use Prettier and you won't have to worry about formatting problems like redundant empty lines.
> 2. The branch name does not match the agreed pattern. Didn't you encounter problems while committing? The branch name is validated and the example of valid name is "tests/ISSUE-16_Post_Login_endpoint_tests"

I removed redundant empty lines.
I noticed that Prettier does not always remove them. 

I did not encounter any problems while committing. During future commits I will follow this  rule. Renaming the current branch would be problematic.

2024-01-28 19:24 UTC, kat-kan submitted a review, later dismissed

2024-02-04 22:00 UTC, bugITwhisperer requested changes

2024-02-04 22:00 UTC, bugITwhisperer commented on tests/api/comments-post.spec.ts
> +});
missing empty line at the end of the file which is a good practice, could you please add it? :)

2024-02-04 22:02 UTC, bugITwhisperer commented
@Justyna-KO : congrats on your 1st PR - great work! 💪🏻 😸

2024-02-05 13:24 UTC, adamcegielka approved these changes

2024-02-12 21:39 UTC, kat-kan approved these changes

2024-02-12 21:39 UTC, kat-kan commented on src/api/enums/api-status-code.enum.ts
> +    Created = 201
I think it would be most convenient to add new codes by groups within the enum (so first 200s - Ok and Created - then 400s)

2024-02-12 23:21 UTC, Justyna-KO commented on src/api/enums/api-status-code.enum.ts
> +    Created = 201
@kat-kan good point, I changed the order.

2024-02-16 12:35 UTC, kat-kan approved these changes

2024-02-16 13:22 UTC, bugITwhisperer approved these changes

2024-02-16 13:24 UTC, bugITwhisperer requested changes

2024-02-16 13:24 UTC, bugITwhisperer commented on tests/api/comments-post.spec.ts
> +  let expectedStatusCode: number;
this line is redundant and can be removed

2024-02-16 13:33 UTC, bugITwhisperer commented on tests/api/comments-post.spec.ts
> +  const comments: string = `${baseUrl}/api/comments`;
Closing since the issue is resolved :)

2024-02-16 13:33 UTC, bugITwhisperer commented on tests/api/comments-post.spec.ts
> +    //When user sends POST request to Comments endpoint
The issue has been fixed, so conversation can be marked as resolved

2024-02-16 13:33 UTC, bugITwhisperer commented on tests/api/comments-post.spec.ts
> +
Closing since the issue is resolved :)

2024-02-16 13:33 UTC, bugITwhisperer commented on tests/api/comments-post.spec.ts
> +    expect(responseBody.id).not.toBeNull;
Closing since the issue is resolved :)

2024-02-16 13:33 UTC, bugITwhisperer commented on tests/api/comments-post.spec.ts
> +    //And
Closing since the issue is resolved :)

2024-02-16 13:33 UTC, bugITwhisperer commented on tests/api/comments-post.spec.ts
> +
Closing since the issue is resolved :)

2024-02-16 13:33 UTC, bugITwhisperer commented on tests/api/comments-post.spec.ts
> +     //And
Closing since the issue is resolved :)

2024-02-16 13:33 UTC, bugITwhisperer commented on tests/api/comments-post.spec.ts
> +
Closing since the issue is resolved :)

2024-02-16 13:33 UTC, bugITwhisperer commented on tests/api/comments-post.spec.ts
> +    expectedStatusCode = 422;
Closing since the issue is resolved :)

2024-02-16 13:33 UTC, bugITwhisperer commented on tests/api/comments-post.spec.ts
> +    //And
Closing since the issue is resolved :)

2024-02-16 13:33 UTC, bugITwhisperer commented on tests/api/comments-post.spec.ts
> +});
@Justyna-KO : this one is still valid, can you add an empty line pls?

2024-02-16 13:33 UTC, bugITwhisperer commented on tests/api/comments-post.spec.ts
> +
Closing since the issue is resolved :)

2024-02-16 13:33 UTC, bugITwhisperer commented on tests/api/comments-post.spec.ts
> +
Closing since the issue is resolved :)

2024-02-16 13:33 UTC, bugITwhisperer commented on tests/api/comments-post.spec.ts
> +  let expectedStatusCode: number;
Closing since the issue is resolved :) I checked the newest changes here: https://github.com/kat-kan/kawqa-gad-playwright/blob/062fd4b4767b71171f0599fc0d02c1227c394746/tests/api/comments-post.spec.ts

2024-02-19 11:05 UTC, bugITwhisperer commented on tests/api/comments-post.spec.ts
> +  let expectedStatusCode: number;
Awesome! Resolving the conversation then :)

2024-02-19 11:08 UTC, bugITwhisperer approved these changes

2024-02-19 14:26 UTC, bugITwhisperer commented on tests/api/comments-post.spec.ts
> +});
Added, resolving issue

2024-02-19 14:26 UTC, bugITwhisperer submitted a review, later dismissed

2024-02-19 15:33 UTC, Justyna-KO commented
> It's good to be merged now :)

I had to make another commit because of the conflict. It needs new approve:-)

2024-02-19 15:39 UTC, bugITwhisperer approved these changes

2024-02-19 16:24 UTC, merged