(tests) : fix broken POST tests after upgrading GAD to v2.5.3
kat-kan/kawqa-gad-playwright pull request #74
Opened 2024-02-18 15:55 UTC by kat-kan

## Resolves #73

- [ ] Describe the purpose and scope of your changes.
2 tests stopped working after upgrading to v2.5.3 GAD, this PR includes fix + improves formatting

- [ ] If it's a new feature, provide instructions on how to use it.
      ...

## Any other comments?

...

Before you submit a Pull Request, please ensure that you do the following:

- [ ] Ensure that the PR is associated with the relevant Issue before its creation.
- [ ] All new and existing tests passed
- [ ] Your commit messages follow the `kawqa-gad-playwright` project's [git commit message format](https://github.com/kat-kan/kawqa-gad-playwright/CONTRIBUTING.md).

2024-02-18 21:06 UTC, bugITwhisperer approved these changes

2024-02-18 21:57 UTC, bugITwhisperer requested changes

2024-02-18 21:57 UTC, bugITwhisperer commented on tests/api/articles-post.spec.ts
> +import { STATUS_CODES } from 'http';
This is not required anymore since we decided not to use external library, right?

2024-02-18 21:57 UTC, bugITwhisperer commented on tests/api/articles-post.spec.ts
>    let expectedStatusCode: number;
This line is redundant

2024-02-19 11:42 UTC, Justyna-KO submitted a review, later dismissed

2024-02-19 12:48 UTC, bugITwhisperer commented on tests/api/articles-post.spec.ts
>    let expectedStatusCode: number;
Or not at all. Since you're using it to store the enum constant

2024-02-19 12:48 UTC, bugITwhisperer submitted a review, later dismissed

2024-02-19 13:49 UTC, Justyna-KO approved these changes

2024-02-19 14:28 UTC, bugITwhisperer approved these changes

2024-02-19 14:28 UTC, bugITwhisperer commented on tests/api/articles-post.spec.ts
> +import { STATUS_CODES } from 'http';
It was removed now :)

2024-02-19 14:35 UTC, merged