Add test for GET comments
kat-kan/kawqa-gad-playwright pull request #81
Opened 2024-03-20 18:57 UTC by kat-kan

## Resolves #80

### Scope of changes:

Quick and easy PR with one new test and packages rearrangement. 

### How to use it:

N/A

## Any other comments?

N/A

Before submitting Pull Request, I've ensured that:

- [ ] The PR is associated with the relevant Issue before its creation.
- [ ] All new and existing tests passed
- [ ] My commit messages follow the `kawqa-gad-playwright` project's [git commit message format](https://github.com/kat-kan/kawqa-gad-playwright/blob/main/CONTRIBUTING.md).

2024-03-20 21:26 UTC, Slawomir-DKl reviewed
This is my first review in Playwright project. Please consider my comments as curiosity only - just beginner's questions

2024-03-20 21:26 UTC, Slawomir-DKl commented on tests/api/articles/articles-post.spec.ts
Do you have PASS status for this test? I had to change the date to the past - for the future date from line `const articleDate: string = '2024-06-30T15:44:31Z';` the test failed with the following message:
```javascript
{
  error: {
    message: 'Date field is invalid: Field validation: "date" has date in future!',
    details: [ 'date' ]
  }
}
```

2024-03-20 21:26 UTC, Slawomir-DKl commented on tests/api/comments/comments-get.spec.ts
> +  const articles: string = `/api/comments`;
Why the constant is called "articles" when you request comments? Is it justified?

2024-03-20 23:05 UTC, kat-kan commented on tests/api/comments/comments-get.spec.ts
> +  const articles: string = `/api/comments`;
Good catch, it's a silly copy-paste mistake :)

2024-03-20 23:07 UTC, kat-kan commented on tests/api/articles/articles-post.spec.ts
All tests were passing for me but I'll double check that

2024-03-23 18:18 UTC, Justyna-KO requested changes
We could stick to the naming convention already started and not use the word 'endpoint' in the test name.
![image](https://github.com/kat-kan/kawqa-gad-playwright/assets/78757947/a59da251-1b43-4dfe-90cc-1ff6cab13ef1)

2024-03-27 19:18 UTC, kat-kan commented on tests/api/articles/articles-post.spec.ts
@Slawomir-DKl thank You for noticing it, I addressed this issue in PR https://github.com/kat-kan/kawqa-gad-playwright/pull/84

2024-04-04 21:03 UTC, kat-kan commented on tests/api/comments/comments-get.spec.ts
> +  const articles: string = `/api/comments`;
@Slawomir-DKl fixed :)

2024-04-04 21:06 UTC, kat-kan commented
@Justyna-KO no idea why I cannot reply in the thread but regarding articles-endpoint-get.spec.ts: after Your comment I noticed that it's the same test as articles-get.spec.ts with some very small differences. So I deleted this file

2024-04-08 18:15 UTC, Slawomir-DKl commented on tests/api/comments/comments-get.spec.ts
> +  const comments: string = `/api/comments`;
I'm just curious - why do you put the string in backticks? Is it a preparation for the future e.g. for entering variables into these strings?

2024-04-08 20:27 UTC, kat-kan commented on tests/api/comments/comments-get.spec.ts
> +  const comments: string = `/api/comments`;
Another good catch ;) 
yup, backticks were not needed here, I wanted a normal string declaration. Fixed

2024-04-08 21:32 UTC, Slawomir-DKl commented on tests/api/articles/articles-get.spec.ts
>    const articles: string = `/api/articles`;
Could you please change these backticks, too? I know they are out of your commits in this PR, but maybe it would be good opportunity to do small refactor :)

2024-04-10 16:13 UTC, kat-kan commented on tests/api/articles/articles-get.spec.ts
>    const articles: string = `/api/articles`;
sure :)

2024-04-10 19:44 UTC, Slawomir-DKl approved these changes

2024-04-17 22:31 UTC, Justyna-KO approved these changes
looks great! the tests are now organized. After your changes in post articles, the test passes. Now patch articles started to fail, but it is not the fault of your changes, so I give approve.

2024-04-18 16:55 UTC, merged