test(comments): add more tests for PATCH/comments
kat-kan/kawqa-gad-playwright pull request #92
Opened 2024-04-20 17:27 UTC by Justyna-KO

## Resolves #89 

### Scope of changes:

-add test: 401Unauthorized -> when invalid token is sent in headers

-add test: 400 Bad Request -> when malformed json is used

-add test: 422 Unprocessable Entity -> when keys are missing and values are too long

-add test 404 Comment not found

### How to use it:

## Any other comments?

Before submitting Pull Request, I've ensured that:

- [ ] The PR is associated with the relevant Issue before its creation.
- [ ] All new and existing tests passed
- [ ] My commit messages follow the `kawqa-gad-playwright` project's [git commit message format](https://github.com/kat-kan/kawqa-gad-playwright/blob/main/CONTRIBUTING.md).

2024-04-21 10:11 UTC, Slawomir-DKl requested changes
Please treat my comments as a beginner's suggestions/questions only :)

2024-04-21 10:11 UTC, Slawomir-DKl commented on tests/api/comments/comments-patch.spec.ts
> +      "article_id": 1,
use the same indent as in other elements of this JSON string

2024-04-21 10:11 UTC, Slawomir-DKl commented on tests/api/comments/comments-patch.spec.ts
> +          body: `${newComment}`,
`body: newComment` should be sufficient - you don't concatenate any other variable to use backticks

2024-04-27 19:23 UTC, Justyna-KO commented
> Please treat my comments as a beginner's suggestions/questions only :)

thank you, very useful comments.
please review again.

2024-05-20 19:57 UTC, Slawomir-DKl approved these changes
Thank you for your changes. In fact, one test fails at the moment, but it comes from the future date in createNewComment() function. I've fixed it in https://github.com/kat-kan/kawqa-gad-playwright/pull/96 (I'm waiting for the Katarzyna's approval of that PR and I expect some nice conflicts, so please merge this PR to main first :) ).

2024-06-16 10:49 UTC, Slawomir-DKl requested changes
I added one suggestion only.

2024-06-16 10:49 UTC, Slawomir-DKl commented on tests/api/comments/comments-patch.spec.ts
> +  let setInvalidHeaders: { [key: string]: string };
This variable is used only in one negative test, therefore I suggest removing its declaration and initialization from `describe` and `beforeAll` and entering `const setInvalidHeaders = await createInvalidHeaders();` into the test "Returns 401 Unauthorized status code when trying to update an existing comments with random text as token"

2024-06-17 06:18 UTC, Slawomir-DKl approved these changes
Thank you for your changes.

2024-06-17 14:01 UTC, merged